---
title: "Assignment 2"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
require(devtools)
if(!require(treemapify)){install_github("wilkox/treemapify")}
df<-read.csv("Modified_Air_Trafic_Data.csv")
df <- df %>% mutate(ArrTime = if_else(is.na(ArrTime), 0L, ArrTime)) %>% mutate(ArrDelay = if_else(is.na(ArrDelay), 0L, if_else(ArrDelay<0, 0L, ArrDelay)))
df <- df %>% mutate(DepTime = if_else(is.na(DepTime), 0L, DepTime)) %>% mutate(DepDelay = if_else(is.na(DepDelay), 0L, if_else(DepDelay<0, 0L, DepDelay)))
df <- df %>% mutate(DepDelayed = if_else(DepDelay>0L, 1L, 0L)) %>% mutate(ArrDelayed = if_else(ArrDelay>0L, 1L, 0L))
```

```{r}
#Question 1 and 2
Week_df<-df %>% 
    group_by( DayOfWeek ) %>% 
    summarise( Count = n(), Avg_ArrTime=mean(ArrTime), Avg_ArrDelay=mean(ArrDelay),  Avg_DepTime=mean(DepTime), Avg_DepDelay=mean(DepDelay))
Month_df<-df %>% 
    group_by( DayofMonth ) %>% 
    summarise( Count = n(), Avg_ArrTime=mean(ArrTime), Avg_ArrDelay=mean(ArrDelay),  Avg_DepTime=mean(DepTime), Avg_DepDelay=mean(DepDelay))
```

```{r}
ggplot(data=Week_df, aes(x=DayOfWeek, y=Avg_ArrDelay)) +geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=round(Avg_ArrDelay, 2)), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+labs(title="Avg Arrival Delay by Day of Week")
```

```{r}
ggplot(data=Week_df, aes(x=DayOfWeek, y=Avg_DepDelay)) +geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=round(Avg_DepDelay, 2)), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+labs(title="Avg Departure Delay by Day of Week")
```

```{r}
ggplot(data=Month_df, aes(x=DayofMonth, y=Avg_ArrDelay)) +geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=round(Avg_ArrDelay, 1)), vjust=1.6, color="white",
            position = position_dodge(0.9), size=2)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+labs(title="Avg Arrival Delay by Day of Month")
```


```{r}
ggplot(data=Month_df, aes(x=DayofMonth, y=Avg_DepDelay)) +geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=round(Avg_DepDelay, 1)), vjust=1.6, color="white",
            position = position_dodge(0.9), size=2)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+labs(title="Avg Departure Delay by Day of Month")
```

```{r}
#Question 3 and 4
Week_df<-df %>% 
    group_by( OriginAirportID ) %>% 
    summarise( Count = n(), Avg_ArrTime=mean(ArrTime), Avg_ArrDelay=mean(ArrDelay),  Avg_DepTime=mean(DepTime), Avg_DepDelay=mean(DepDelay), ArrDelayed=sum(ArrDelayed),
               DepDelayed=sum(DepDelayed))
```

```{r}
ggplot(Week_df, aes(area = ArrDelayed, fill = ArrDelayed, label = paste(OriginAirportID,ArrDelayed,sep="\n"))) +
  geom_treemap(colour="blue", ) +
  geom_treemap_text(
    fontface = "italic",
    colour = "white",
    place = "centre",
    grow = TRUE
  )+labs(title="Origin Airport by Total Arrival Delays")

```

```{r}
ggplot(Week_df, aes(area = DepDelayed, fill = DepDelayed, label = paste(OriginAirportID,DepDelayed,sep="\n"))) +
  geom_treemap(colour="blue") +
  geom_treemap_text(
    fontface = "italic",
    colour = "white",
    place = "centre",
    grow = TRUE
  )+labs(title="Origin Airport by Total Departure Delays")

```

```{r}
#Question 5
df<-read.csv("Modified_Air_Trafic_Data.csv")
ggplot(df, aes(ArrDelay, Distance)) + 
  geom_point(aes(colour= "blue"))+
  facet_wrap(~OriginAirportID)+labs(title="Origin Airports by Distance vs Arrival Delays")+xlab("Arrival Delay") + ylab("Distance")

```

```{r}
#Question 6
df<-read.csv("Modified_Air_Trafic_Data.csv")
ggplot(df, aes(CarrierDelay_mod, WeatherDelayMod)) + 
  geom_point(aes(colour= "blue"))+labs(title="Cities by Carrier Delay vs Weather Delay")+xlab("Carrier Delay") + ylab("Weather Delay")

cor(df[, c("CarrierDelay_mod")], df[, c("WeatherDelayMod")]) 

```

```{r}
#Question 7
df<-read.csv("Modified_Air_Trafic_Data.csv")
df <- df %>% mutate(ArrTime = if_else(is.na(ArrTime), 0L, ArrTime)) %>% mutate(ArrDelay = if_else(is.na(ArrDelay), 0L, if_else(ArrDelay<0, 0L, ArrDelay)))
df <- df %>% mutate(DepTime = if_else(is.na(DepTime), 0L, DepTime)) %>% mutate(DepDelay = if_else(is.na(DepDelay), 0L, if_else(DepDelay<0, 0L, DepDelay)))
df <- df %>% mutate(DepDelayed = if_else(DepDelay>0L, 1L, 0L)) %>% mutate(ArrDelayed = if_else(ArrDelay>0L, 1L, 0L))
State_df<-df %>% 
    group_by( Region, DayOfWeek ) %>% 
    summarise( Count = n(), Avg_ArrTime=mean(ArrTime), Avg_ArrDelay=mean(ArrDelay),  Avg_DepTime=mean(DepTime), Avg_DepDelay=mean(DepDelay))
ggplot(State_df, aes(DayOfWeek, Avg_ArrDelay)) +geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=round(Avg_ArrDelay, 1)), vjust=1.6, color="white",
            position = position_dodge(0.9), size=2)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+
  facet_wrap(~Region)+labs(title="Delay Pattern by State")+xlab("Day of the Week") + ylab("Arrival Delay")

```

```{r}
#Question 8 and 9
df<-read.csv("Modified_Air_Trafic_Data.csv")
df <- df %>% mutate(ArrTime = if_else(is.na(ArrTime), 0L, ArrTime)) %>% mutate(ArrDelay = if_else(is.na(ArrDelay), 0L, if_else(ArrDelay<0, 0L, ArrDelay)))
df <- df %>% mutate(DepTime = if_else(is.na(DepTime), 0L, DepTime)) %>% mutate(DepDelay = if_else(is.na(DepDelay), 0L, if_else(DepDelay<0, 0L, DepDelay)))
df <- df %>% mutate(DepDelayed = if_else(DepDelay>0L, 1L, 0L)) %>% mutate(ArrDelayed = if_else(ArrDelay>0L, 1L, 0L))
cancelled_df<-df %>% 
    filter(DepDelay>0) %>% filter(Cancelled==1) %>% 
    summarise( Count = n())
diverted_df<-df %>% 
    filter(DepDelay>0) %>% filter(Diverted==1) %>% 
    summarise( Count = n())
cancelled_df
diverted_df
```

```{r}
#Question 10 and 11
df<-read.csv("Modified_Air_Trafic_Data.csv")
df <- df %>% mutate(ArrTime = if_else(is.na(ArrTime), 0L, ArrTime)) %>% mutate(ArrDelay = if_else(is.na(ArrDelay), 0L, if_else(ArrDelay<0, 0L, ArrDelay)))
df <- df %>% mutate(DepTime = if_else(is.na(DepTime), 0L, DepTime)) %>% mutate(DepDelay = if_else(is.na(DepDelay), 0L, if_else(DepDelay<0, 0L, DepDelay)))
df <- df %>% mutate(DepDelayed = if_else(DepDelay>0L, 1L, 0L)) %>% mutate(ArrDelayed = if_else(ArrDelay>0L, 1L, 0L))
Dep_CRS_df<-df %>% 
    filter(DepDelay>0) %>% group_by( CRSDepTime )%>%
    summarise( Count = n())
Arr_CRS_df<-df %>% 
    filter(ArrDelay>0) %>% group_by( CRSArrTime )%>%
    summarise( Count = n())

```

```{r}
ggplot(data=Dep_CRS_df, aes(x=CRSDepTime, y=Count)) +geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Count), vjust=1.6, color="white",
            position = position_dodge(0.9), size=2)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+labs(title="Time of Day for Departure Delays")

```

```{r}
ggplot(data=Arr_CRS_df, aes(x=CRSArrTime, y=Count)) +geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Count), vjust=1.6, color="white",
            position = position_dodge(0.9), size=2)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+labs(title="Time of Day for Arrival Delays")

```